version: "3.9"

services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - "es"
    links:
      - "es"
  
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node